<?xml version="1.0" encoding="UTF-8"?>
<Algo>
    <description texte="" courant="mois[ JANVIER : FEVRIER : MARS : AVRIL : MAI : JUIN : AOUT : SEPTEMBRE : OCTOBRE : NOVEMBRE : DECEMBRE ] PREND_LA_VALEUR  JANVIER , FEVRIER , MARS , AVRIL , MAI , JUIN , AOUT :,SEPTEMBRE , OCTOBRE , NOVEMBRE , DECEMBRE "/>
    <extension extnom="inactif"/>
    <fonction fctetat="inactif" fctcode=""/>
    <F2 F2etat="inactif" F2lignes="" F2defaut="" F2para=""/>
    <repere repcode="-10#10#-10#10#2#2" repetat="inactif"/>
    <param totalBoucles="5000000" epaisseurPoint="2" arrondiAuto="vrai" nbDecimales="8" maxBoucle="500000" totalAffichages="1000" epaisseurLigne="2"/>
    <item code="200#declarationfonctions" algoitem="FONCTIONS_UTILISEES"/>
    <item code="100#declarationsvariables" algoitem="VARIABLES">
        <item code="1#LISTE#mois" algoitem="mois EST_DU_TYPE LISTE"/>
    </item>
    <item code="101#debutalgo" algoitem="DEBUT_ALGORITHME">
        <item code="5#mois# JANVIER , FEVRIER , MARS , AVRIL , MAI , JUIN , AOUT :,SEPTEMBRE , OCTOBRE , NOVEMBRE , DECEMBRE # JANVIER : FEVRIER : MARS : AVRIL : MAI : JUIN : AOUT : SEPTEMBRE : OCTOBRE : NOVEMBRE : DECEMBRE " algoitem="mois[ JANVIER : FEVRIER : MARS : AVRIL : MAI : JUIN : AOUT : SEPTEMBRE : OCTOBRE : NOVEMBRE : DECEMBRE ] PREND_LA_VALEUR  JANVIER , FEVRIER , MARS , AVRIL , MAI , JUIN , AOUT :,SEPTEMBRE , OCTOBRE , NOVEMBRE , DECEMBRE "/>
    </item>
    <item code="102#finalgo" algoitem="FIN_ALGORITHME"/>
</Algo>
